# .github/workflows/manual-test.yml
name: "Execução Manual - Testes JS"

on: workflow_dispatch

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes e gerar JUnit XML
        run: npm test

      - name: Publicar teste como relatório no GitHub
        uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: reports/junit/results.xml
