name: "Execução Manual - Testes JS"

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # 1) Puxa o código
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # 2) Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      # 3) Instala dependências
      - name: Instalar dependências
        run: npm ci

      # 4) Executa testes e gera o XML
      - name: Executar testes (gera JUnit XML)
        run: npm test

      # 5) Publica sumário inline no Actions
      - name: Publicar relatório no GitHub Checks
        uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: reports/junit/results.xml

      # 6) Faz o upload do XML como artefato (para download)
      - name: Upload do relatório JUnit XML
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: reports/junit/results.xml
