name: "Execução Manual - Testes JS"

# 1) Declare quando este workflow deve ser reconhecido
on:
  workflow_dispatch: # para Run workflow manual
  push: # opcional: roda automaticamente em push na main
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes (gera JUnit XML)
        run: npm test

      - name: Publicar relatório no GitHub Checks
        uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: reports/junit/results.xml

      - name: Upload do relatório JUnit XML
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit/results.xml
