# Execução Agendada de Testes E2E
name: "Execução Agendada - Testes E2E"

on:
  schedule:
    - cron: "0 6 * * 1" # Segunda-feira às 06:00 UTC
  workflow_dispatch: # Permite execução manual

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes E2E
        run: npm test

      - name: Upload de evidências E2E (prints/logs/etc)
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-e2e
          path: reports/junit
